### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by aaronbronow** [bholt/Github-Markdown.tmbundle#1]
Hi, I am getting this message appended at the bottom of my preview when I preview in TextMate 2.0-rc.4

`[WARNING] Deprecated: markdown_github. Use gfm instead. [WARNING] This document format requires a nonempty`

**Comment by bholt** [comment]
Thanks for catching this! I hadn't used the preview command in a while. I just updated the preview command to use "gfm" instead.
